version: '2'
services:
  shop:
    image: containerbank.azurecr.io/shop/front:BuildNumber
    environment:
      - SHOP_PRODUCTS_API_URL=http://localhost/products/
      - SHOP_RATINGS_API_URL=http://localhost/ratings/
      - SHOP_RECOMMANDATIONS_API_URL=http://localhost/recommandations/
  products:
    image: containerbank.azurecr.io/shop/products-api:BuildNumber
  ratings:
    image: containerbank.azurecr.io/shop/ratings-api:BuildNumber
  recommandations:
    image: containerbank.azurecr.io/shop/recommandations-api:BuildNumber
  inventory:
    image: containerbank.azurecr.io/shop/inventory:BuildNumber
    ports: ["12000:80"]
  proxy:
    image: containerbank.azurecr.io/shop/nginx-proxy:latest
    ports: ["80:80"]
